### ISSUE TITLE
Define structured way to host plug-in meta-data

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler-plugins#66]
__What shall we do__

As a integration author I love to discover available plug-ins in a structured manner. At the same time I'd like to understand an individual plug-ins context (i.e. compatibility) in a structured manner (currently represented as a [compat table](https://github.com/bpmn-io/bpmn-js-token-simulation-plugin#compatibility-notice) + badge)), too.

__Why shall we do it__

Providing both in a structured way allows us to build tooling for plug-in discovery, installation, and upgrading (i.e. [`mopl`](https://github.com/pinussilvestrus/mopl), just without crawling).

**Comment by pinussilvestrus** [comment]
The easiest thing would be to have a `plugins.json` at the root of this project that provides this metadata. [Other projects provide this via yml](https://github.com/electron/apps/blob/master/apps/camunda-modeler/camunda-modeler.yml), which could be interesting as well.

I will research this thing a bit.

**Comment by pinussilvestrus** [comment]
### How others do

**VS Code Marketplace**
* any plugin defines itself
* no central, easy accessible registry
* only example repo: https://github.com/microsoft/vscode-extension-samples

**Electron Apps**
https://github.com/electron/apps/blob/master/apps/camunda-modeler/camunda-modeler.yml
* define via yml
* one file per app
	
```yml
name: 'Camunda Modeler'
description:
  'Developer-friendly app for editing and executing BPMN process diagrams and
  DMN decisions.'
website: 'https://camunda.com/products/modeler/'
category: 'Developer Tools'
repository: 'https://github.com/camunda/camunda-modeler/'
keywords:
  - bpmn
  - dmn
  - modeling
  - modeler
  - diagram
  - 'business process'
license: MIT
screenshots:
  - imageUrl: 'https://raw.githubusercontent.com/camunda/camunda-modeler/master/docs/screenshot.png'
    caption: 'BPMN Editor with properties panel'
    imageLink: 'https://github.com/camunda/camunda-modeler'
```
	
**JSON Schema Catalog**
https://github.com/SchemaStore/schemastore/blob/master/src/api/json/catalog.json
* define via json
* simple overview, easily accessible
* maintains versions, but no compatibility 

```json
{
  "$schema": "https://json.schemastore.org/schema-catalog.json",
  "version": 1.0,
  "schemas": [
    {
      "name": "AnyWork Automation Configuration",
      "description": "AnyWork Automation Configuration used to configure automation scripts on AnyWork",
      "fileMatch": [
        ".awc.yaml",
        ".awc.yml",
        ".awc.json",
        ".awc.jsonc",
        ".awc"
      ],
      "url": "https://json.schemastore.org/anywork-ac-1.1.json",
      "versions": {
         "1.0": "https://json.schemastore.org/anywork-ac-1.0.json"
      }
    },
    ...
  ]
}
```

**Fig Plugins**
https://github.com/withfig/plugins/blob/main/CONTRIBUTING.md#add-metadata-to-your-plugin
* define via index.ts 
* quite complex
* interesting: stores the complete plugin installation guide inside the plugins/ sub directory
	
```ts
const plugin: Fig.Plugin = {
  icon: "🔗",
  name: "dropbox_zpm-zsh",
  displayName: "Dropbox (ZPM)",
  type: "shell",
  description: "Zsh dropbox plugin",
  authors: [
    {
      name: "zpm-zsh",
      github: "zpm-zsh",
    },
  ],
  github: "zpm-zsh/dropbox",
  license: ["GPL-3.0"],
  site: "https://github.com/horosgrisa/zsh-dropbox",
  shells: ["zsh"],
  categories: ["Completion"],
  keywords: ["zsh", "dropbox-plugin", "dropbox"],
  installation: {
    origin: "github",
    sourceFiles: ["dropbox.plugin.zsh"],
  },
};

export default plugin;
```
	
**Obsidians Community Plugins**
https://github.com/obsidianmd/obsidian-releases/blob/master/community-plugins.json
* define via json
* simple overview
	
```json
[
    {
        "id": "nldates-obsidian",
        "name": "Natural Language Dates",
        "author": "Argentina Ortega Sainz",
        "description": "Create date-links based on natural language",
        "repo": "argenos/nldates-obsidian"
    },
    {
        "id": "hotkeysplus-obsidian",
        "name": "Hotkeys++",
        "author": "Argentina Ortega Sainz",
        "description": "Additional hotkeys to do common things in Obsidian",
        "repo": "argenos/hotkeysplus-obsidian"
    },
    ...
]
```
